// src/pages/Settings.tsx
import { useState, useEffect } from 'react'
import { 
  Settings as SettingsIcon, 
  Download, 
  Trash2, 
  RefreshCw,
  Smartphone,
  Globe,
  Type,
  Palette
} from 'lucide-react'
import { useTranslation } from 'react-i18next'
import { useOffline } from '../hooks/useOffline'
import { OfflineStatus } from '../components/OfflineStatus'
import { LanguageSelector } from '../components/LanguageSelector'
import { useLanguage } from '../hooks/useLanguage'

export function Settings() {
  const { t } = useTranslation()
  const { currentLanguage, getCurrentLanguage } = useLanguage()
  const {
    isOnline,
    isInstalled,
    canInstall,
    cacheSize,
    lastSync,
    installApp,
    clearCache,
    syncOfflineContent,
    checkCacheSize
  } = useOffline()

  const [fontSize, setFontSize] = useState('medium')
  const [theme, setTheme] = useState('light')
  const [isLoading, setIsLoading] = useState(false)

  // Carregar configurações do localStorage
  useEffect(() => {
    const savedFontSize = localStorage.getItem('bible-app-font-size') || 'medium'
    const savedTheme = localStorage.getItem('bible-app-theme') || 'light'
    
    setFontSize(savedFontSize)
    setTheme(savedTheme)
    
    // Aplicar tema
    document.documentElement.setAttribute('data-theme', savedTheme)
  }, [])

  const handleFontSizeChange = (newSize: string) => {
    setFontSize(newSize)
    localStorage.setItem('bible-app-font-size', newSize)
    
    // Aplicar tamanho da fonte
    document.documentElement.setAttribute('data-font-size', newSize)
  }

  const handleThemeChange = (newTheme: string) => {
    setTheme(newTheme)
    localStorage.setItem('bible-app-theme', newTheme)
    
    // Aplicar tema
    document.documentElement.setAttribute('data-theme', newTheme)
  }

  const handleInstall = async () => {
    setIsLoading(true)
    try {
      await installApp()
    } catch (error) {
      console.error('Erro ao instalar:', error)
    } finally {
      setIsLoading(false)
    }
  }

  const handleClearCache = async () => {
    setIsLoading(true)
    try {
      await clearCache()
    } catch (error) {
      console.error('Erro ao limpar cache:', error)
    } finally {
      setIsLoading(false)
    }
  }

  const handleSync = async () => {
    setIsLoading(true)
    try {
      await syncOfflineContent()
    } catch (error) {
      console.error('Erro na sincronização:', error)
    } finally {
      setIsLoading(false)
    }
  }

  const formatBytes = (bytes: number): string => {
    if (bytes === 0) return '0 Bytes'
    const k = 1024
    const sizes = ['Bytes', 'KB', 'MB', 'GB']
    const i = Math.floor(Math.log(bytes) / Math.log(k))
    return parseFloat((bytes / Math.pow(k, i)).toFixed(2)) + ' ' + sizes[i]
  }

  const formatDate = (date: Date | null): string => {
    if (!date) return 'Nunca'
    return new Intl.DateTimeFormat('pt-BR', {
      day: '2-digit',
      month: '2-digit',
      year: 'numeric',
      hour: '2-digit',
      minute: '2-digit'
    }).format(date)
  }

  const currentLang = getCurrentLanguage()

  return (
    <div className="max-w-4xl mx-auto space-y-6">
      <div className="text-center">
        <h1 className="text-3xl font-bold text-gray-900 mb-4 flex items-center justify-center">
          <SettingsIcon className="w-8 h-8 mr-3" />
          Configurações
        </h1>
        <p className="text-gray-600">Personalize sua experiência de leitura</p>
      </div>

      {/* Aparência */}
      <div className="card">
        <h2 className="text-xl font-semibold text-gray-900 mb-4 flex items-center">
          <Palette className="w-5 h-5 mr-2" />
          Aparência
        </h2>
        
        <div className="space-y-6">
          {/* Tamanho da Fonte */}
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-3">
              Tamanho da fonte
            </label>
            <div className="grid grid-cols-2 md:grid-cols-4 gap-2">
              {[
                { value: 'small', label: 'Pequeno' },
                { value: 'medium', label: 'Médio' },
                { value: 'large', label: 'Grande' },
                { value: 'xlarge', label: 'Muito Grande' }
              ].map((option) => (
                <button
                  key={option.value}
                  onClick={() => handleFontSizeChange(option.value)}
                  className={`px-4 py-2 rounded-lg text-sm font-medium transition-colors ${
                    fontSize === option.value
                      ? 'bg-primary-600 text-white'
                      : 'bg-gray-100 text-gray-700 hover:bg-gray-200'
                  }`}
                >
                  {option.label}
                </button>
              ))}
            </div>
          </div>

          {/* Tema */}
          <div>
            <label className="block text-sm font-medium text-gray-700 mb-3">
              Tema
            </label>
            <div className="grid grid-cols-2 gap-2">
              {[
                { value: 'light', label: 'Claro' },
                { value: 'dark', label: 'Escuro' }
              ].map((option) => (
                <button
                  key={option.value}
                  onClick={() => handleThemeChange(option.value)}
                  className={`px-4 py-2 rounded-lg text-sm font-medium transition-colors ${
                    theme === option.value
                      ? 'bg-primary-600 text-white'
                      : 'bg-gray-100 text-gray-700 hover:bg-gray-200'
                  }`}
                >
                  {option.label}
                </button>
              ))}
            </div>
          </div>
        </div>
      </div>

      {/* Idioma */}
      <div className="card">
        <h2 className="text-xl font-semibold text-gray-900 mb-4 flex items-center">
          <Globe className="w-5 h-5 mr-2" />
          Idioma
        </h2>
        
        <div className="space-y-4">
          <div className="flex items-center justify-between">
            <div>
              <h3 className="font-medium text-gray-900">Idioma da interface</h3>
              <p className="text-sm text-gray-600">
                {currentLang?.flag} {currentLang?.name}
              </p>
            </div>
            <LanguageSelector />
          </div>
        </div>
      </div>

      {/* Funcionalidades Offline */}
      <div className="card">
        <h2 className="text-xl font-semibold text-gray-900 mb-4 flex items-center">
          <Smartphone className="w-5 h-5 mr-2" />
          Funcionalidades Offline
        </h2>
        
        <OfflineStatus />
      </div>

      {/* Informações do App */}
      <div className="card">
        <h2 className="text-xl font-semibold text-gray-900 mb-4">
          Informações do App
        </h2>
        
        <div className="space-y-4">
          <div className="flex items-center justify-between">
            <span className="text-sm text-gray-600">Versão:</span>
            <span className="text-sm font-medium">1.0.0</span>
          </div>
          
          <div className="flex items-center justify-between">
            <span className="text-sm text-gray-600">Status da conexão:</span>
            <span className={`text-sm font-medium ${
              isOnline ? 'text-green-600' : 'text-red-600'
            }`}>
              {isOnline ? 'Online' : 'Offline'}
            </span>
          </div>
          
          <div className="flex items-center justify-between">
            <span className="text-sm text-gray-600">App instalado:</span>
            <span className={`text-sm font-medium ${
              isInstalled ? 'text-green-600' : 'text-gray-600'
            }`}>
              {isInstalled ? 'Sim' : 'Não'}
            </span>
          </div>
          
          <div className="flex items-center justify-between">
            <span className="text-sm text-gray-600">Tamanho do cache:</span>
            <span className="text-sm font-medium">{formatBytes(cacheSize)}</span>
          </div>
          
          <div className="flex items-center justify-between">
            <span className="text-sm text-gray-600">Última sincronização:</span>
            <span className="text-sm font-medium">{formatDate(lastSync)}</span>
          </div>
        </div>
      </div>

      {/* Ações */}
      <div className="card">
        <h2 className="text-xl font-semibold text-gray-900 mb-4">
          Ações
        </h2>
        
        <div className="space-y-3">
          {canInstall && !isInstalled && (
            <button
              onClick={handleInstall}
              disabled={isLoading}
              className="btn-primary w-full flex items-center justify-center"
            >
              {isLoading ? (
                <RefreshCw className="w-4 h-4 mr-2 animate-spin" />
              ) : (
                <Download className="w-4 h-4 mr-2" />
              )}
              Instalar App
            </button>
          )}
          
          <button
            onClick={handleSync}
            disabled={isLoading || !isOnline}
            className="btn-secondary w-full flex items-center justify-center"
          >
            {isLoading ? (
              <RefreshCw className="w-4 h-4 mr-2 animate-spin" />
            ) : (
              <RefreshCw className="w-4 h-4 mr-2" />
            )}
            Sincronizar Conteúdo
          </button>
          
          <button
            onClick={handleClearCache}
            disabled={isLoading}
            className="btn-secondary w-full flex items-center justify-center text-red-600 hover:text-red-700"
          >
            {isLoading ? (
              <RefreshCw className="w-4 h-4 mr-2 animate-spin" />
            ) : (
              <Trash2 className="w-4 h-4 mr-2" />
            )}
            Limpar Cache
          </button>
        </div>
      </div>
    </div>
  )
}

// src/pages/Settings.vue
<template>
  <q-page class="q-pa-md">
    <div class="q-mb-md">
      <h4 class="text-h4 q-mb-sm">Configurações</h4>
      <p class="text-grey-6">Personalize sua experiência de leitura</p>
    </div>

    <q-card class="q-mb-md">
      <q-card-section>
        <div class="text-h6 q-mb-md">Aparência</div>
        
        <q-list>
          <q-item>
            <q-item-section>
              <q-item-label>Tamanho da fonte</q-item-label>
              <q-item-label caption>Escolha o tamanho ideal para leitura</q-item-label>
            </q-item-section>
            <q-item-section side>
              <q-btn-toggle
                v-model="fontSize"
                :options="[
                  { label: 'Pequeno', value: 'small' },
                  { label: 'Médio', value: 'medium' },
                  { label: 'Grande', value: 'large' }
                ]"
                color="primary"
                @update:model-value="updateFontSize"
              />
            </q-item-section>
          </q-item>

          <q-item>
            <q-item-section>
              <q-item-label>Tema</q-item-label>
              <q-item-label caption>Escolha entre tema claro ou escuro</q-item-label>
            </q-item-section>
            <q-item-section side>
              <q-btn-toggle
                v-model="theme"
                :options="[
                  { label: 'Claro', value: 'light' },
                  { label: 'Escuro', value: 'dark' }
                ]"
                color="primary"
                @update:model-value="updateTheme"
              />
            </q-item-section>
          </q-item>
        </q-list>
      </q-card-section>
    </q-card>

    <q-card class="q-mb-md">
      <q-card-section>
        <div class="text-h6 q-mb-md">Idioma</div>
        
        <q-list>
          <q-item clickable @click="showLanguageDialog = true">
            <q-item-section>
              <q-item-label>Idioma da interface</q-item-label>
              <q-item-label caption>{{ currentLanguageLabel }}</q-item-label>
            </q-item-section>
            <q-item-section side>
              <q-icon name="chevron_right" />
            </q-item-section>
          </q-item>
        </q-list>
      </q-card-section>
    </q-card>

    <q-card class="q-mb-md">
      <q-card-section>
        <div class="text-h6 q-mb-md">Dados Offline</div>
        
        <q-list>
          <q-item>
            <q-item-section>
              <q-item-label>Capítulos salvos</q-item-label>
              <q-item-label caption>{{ offlineStats?.chaptersCount || 0 }} capítulos</q-item-label>
            </q-item-section>
          </q-item>

          <q-item>
            <q-item-section>
              <q-item-label>Favoritos</q-item-label>
              <q-item-label caption>{{ offlineStats?.favoritesCount || 0 }} versículos</q-item-label>
            </q-item-section>
          </q-item>

          <q-item>
            <q-item-section>
              <q-item-label>Última sincronização</q-item-label>
              <q-item-label caption>{{ formatDate(offlineStats?.lastSync) }}</q-item-label>
            </q-item-section>
          </q-item>

          <q-item>
            <q-item-section>
              <q-btn
                color="primary"
                label="Pré-carregar Capítulos Populares"
                @click="preloadChapters"
                :loading="isPreloading"
                :disable="!isOnline"
              />
            </q-item-section>
          </q-item>

          <q-item>
            <q-item-section>
              <q-btn
                color="negative"
                label="Limpar Dados Offline"
                @click="clearOfflineData"
                :disable="!offlineStats?.hasOfflineData"
              />
            </q-item-section>
          </q-item>
        </q-list>
      </q-card-section>
    </q-card>

    <!-- Language Dialog -->
    <q-dialog v-model="showLanguageDialog">
      <q-card>
        <q-card-section>
          <div class="text-h6">Selecionar Idioma</div>
        </q-card-section>

        <q-card-section>
          <q-list>
            <q-item clickable v-close-popup @click="changeLanguage('pt-BR')">
              <q-item-section avatar>
                <q-icon name="flag" color="primary" />
              </q-item-section>
              <q-item-section>
                <q-item-label>🇧🇷 Português</q-item-label>
              </q-item-section>
            </q-item>

            <q-item clickable v-close-popup @click="changeLanguage('en-US')">
              <q-item-section avatar>
                <q-icon name="flag" color="primary" />
              </q-item-section>
              <q-item-section>
                <q-item-label>🇺🇸 English</q-item-label>
              </q-item-section>
            </q-item>

            <q-item clickable v-close-popup @click="changeLanguage('es-ES')">
              <q-item-section avatar>
                <q-icon name="flag" color="primary" />
              </q-item-section>
              <q-item-section>
                <q-item-label>🇪🇸 Español</q-item-label>
              </q-item-section>
            </q-item>
          </q-list>
        </q-card-section>
      </q-card>
    </q-dialog>
  </q-page>
</template>

<script>
import { defineComponent, ref, computed } from 'vue'
import { useI18n } from 'vue-i18n'
import { useOfflineStatus } from '../hooks/useBibleApi'
import { useQuasar } from 'quasar'

export default defineComponent({
  name: 'SettingsPage',

  setup() {
    const { locale } = useI18n()
    const $q = useQuasar()
    const { offlineStats, preloadPopularChapters, clearOfflineData, isOnline } = useOfflineStatus()
    
    const fontSize = ref('medium')
    const theme = ref('light')
    const showLanguageDialog = ref(false)
    const isPreloading = ref(false)

    const currentLanguageLabel = computed(() => {
      const labels = {
        'pt-BR': '🇧🇷 Português',
        'en-US': '🇺🇸 English',
        'es-ES': '🇪🇸 Español'
      }
      return labels[locale.value] || 'Português'
    })

    const changeLanguage = (lang) => {
      locale.value = lang
    }

    const updateFontSize = (size) => {
      // Implementar mudança de tamanho da fonte
      console.log('Font size changed to:', size)
    }

    const updateTheme = (newTheme) => {
      $q.dark.set(newTheme === 'dark')
    }

    const preloadChapters = async () => {
      isPreloading.value = true
      try {
        await preloadPopularChapters()
        $q.notify({
          type: 'positive',
          message: 'Capítulos pré-carregados com sucesso!'
        })
      } catch (error) {
        $q.notify({
          type: 'negative',
          message: 'Erro ao pré-carregar capítulos'
        })
      } finally {
        isPreloading.value = false
      }
    }

    const clearOfflineData = async () => {
      $q.dialog({
        title: 'Confirmar',
        message: 'Tem certeza que deseja limpar todos os dados offline? Esta ação não pode ser desfeita.',
        cancel: true,
        persistent: true
      }).onOk(async () => {
        try {
          await clearOfflineData()
          $q.notify({
            type: 'positive',
            message: 'Dados offline limpos com sucesso!'
          })
        } catch (error) {
          $q.notify({
            type: 'negative',
            message: 'Erro ao limpar dados offline'
          })
        }
      })
    }

    const formatDate = (date) => {
      if (!date) return 'Nunca'
      return new Intl.DateTimeFormat('pt-BR', {
        day: '2-digit',
        month: '2-digit',
        year: 'numeric',
        hour: '2-digit',
        minute: '2-digit'
      }).format(new Date(date))
    }

    return {
      fontSize,
      theme,
      showLanguageDialog,
      isPreloading,
      currentLanguageLabel,
      offlineStats,
      isOnline,
      changeLanguage,
      updateFontSize,
      updateTheme,
      preloadChapters,
      clearOfflineData,
      formatDate
    }
  }
})
</script>
